name: Zipline CI (Windows)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: [3.6]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Init Conda in Powershell
      run: |
        C:\Miniconda\condabin\conda.bat init powershell
    - name: Install scientific python requirements
      run: |
        conda create -y --name test python=${{matrix.python-version}} pip pandas numpy scipy cython=0.29.21
    - name: Install requirements
      run: |
        conda activate test
        pip install --no-binary=bcolz -e .[dev]
    - name: Run tests
      run: |
        conda activate test
        nosetests tests
